// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _RsemanticLibrarian_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rowSumsSq
NumericVector rowSumsSq(NumericMatrix x);
RcppExport SEXP _RsemanticLibrarian_rowSumsSq(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rowSumsSq(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RsemanticLibrarian_rcpp_hello_world", (DL_FUNC) &_RsemanticLibrarian_rcpp_hello_world, 0},
    {"_RsemanticLibrarian_rowSumsSq", (DL_FUNC) &_RsemanticLibrarian_rowSumsSq, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RsemanticLibrarian(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
